### PR TITLE
Changing every componentWillReceiveProps to UNSAFE_componentWillReceiveProp, as the former generates a warning on the console.

### PR DESCRIPTION
**Pull request by afcjunior**
Solves this issue -> https://github.com/YouCanBookMe/react-datetime/issues/673

### Description

This pull request removes the annoying console warning about the componentWillReceiveProp lifecycle method being unsafe. I ran `npx react-codemod rename-unsafe-lifecycles` and then add ed comments to have lint ignore the lack of camelcasing on every `UNSAFE_componentWillReceiveProp` call. 

### Motivation and Context

Solves this issue -> https://github.com/YouCanBookMe/react-datetime/issues/649

### Checklist

```
[X] I have not included any built dist files (us maintainers do that prior to a new release)
```

```
[X] I have added tests covering my changes
```
**No need as I didn't make any meaningful changes.**

```
[ ] All new and existing tests pass
```
**Tests aren't passing due to a pre-existing issue in master, which is solved here -> https://github.com/YouCanBookMe/react-datetime/pull/684 . Once that's merged, I can update this branch so it will pass the CI too.**

```
[X] My changes required the documentation to be updated
```
**nope**

### CODE REVIEW

**Comment by davidcostadev** [comment]
@afcjunior Could you fix the CI?

**Comment by davidcostadev** [comment]
There's some problem master branch, if you push and run the tests it'll break, it needs to fixed on master first.

**Comment by afcjunior** [comment]
https://github.com/YouCanBookMe/react-datetime/pull/684 <-- This pull request fixes the problem master has, which is causing tests to fail.

After it gets merged, I'll update this pull request to include those changes, which will allow it to pass through the CI.

And then we won't have warnings on the console anymore (yay).

**Comment by arqex** [comment]
I have just approved #684

**Comment by afcjunior** [comment]
I rebased with master and it's still failing tests. No clue as to why. 

I tried changing my node to v8, clean npm installing based on the lastest package-lock merge, updating snapshots, rebuilding, and commiting it all. 

Will need to look into it later on today. (Btw I'll squash these commits once I figure out what's messing with the tests)

**Comment by arqex** [comment]
Thanks @afcjunior

Maybe it's simpler to close this PR and open a new one just forking from the last in master?

**Comment by arqex** [comment]
Thanks for the patience. All `componentWillReceiveProps` methods have been removed from version 3. Closing here.

**Pull request closed without merging**
