### PR TITLE
Feature/close on date selection

### PR DESCRIPTION
**Pull request by gcedo**
Hi!

The goal of this PR is to have the DatePicker closing automatically on selection. 

To achieve this, I have added the `closeOnSelect ` prop: When `true`, once the day has been selected, the DatePicker will automatically close.

Cheers,
Edo

### CODE REVIEW

**Comment by graup** [comment]
+1

**Comment by dmatteo** [comment]
Hey @arqex, are you still maintaining the repo or you don't have time anymore?

**Comment by arqex** [comment]
Thanks @gcedo , sorry for the delay. Merging PRs in not so time consuming, but still looking for maintainer...

**Comment by dmatteo** [comment]
If we're talking about reviewing PRs, issues and small maintenance, I can
chip in.

If you need active development and evolution, than I also have to bail out
since I don't have that much free time to help you.

**Pull request merged**
