### PR TITLE
Fix tests and replace travis with github actions

### LINKED ISSUE #780: Tests fail with latest master 7e30d6c
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. `git clone git@github.com:arqex/react-datetime.git`
2. `cd react-datetime`
3. `npm install`
4. `npm run test:all`

### Expected Results

Tests pass

### Actual Results

Tests fail

```
Test Suites: 2 failed, 1 passed, 3 total
Tests:       26 failed, 2 skipped, 121 passed, 149 total
Snapshots:   24 failed, 1 passed, 25 total
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 

This is with latest master https://github.com/arqex/react-datetime/commit/7e30d6c20cd864bf8e91bc94e6c3a0ee02864d19 using node version: v14.15.5

The same commit as ran on CI here https://travis-ci.org/github/arqex/react-datetime/builds/747440775 
CI runs those tests with node 8 and latest stable (v15.3.0)

One thing that makes it hard to reproduce test results is there is no lock file committed to the project. So there is no way to tell if there are dependency issues causing failures.

I would like to propose:

- We commit the npm lock file (or yarn if the maintainers prefer)
- We add Dependabot (or another dependency manager) to the repo. Its free, and makes dependency updating straightforward https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

I think if we make these changes then it will be easier to contribute back while ensuring code quality with reliable tests.

### PR DESCRIPTION
**Pull request by anajavi**
Upgrade testing tools to latest versions

### Description
- Upgrade babel, jest & testing-library to latest versions.
- Set react@^16.14.0 as testing target. 
- resolve-url-loader was upgraded too to get rid of npm audit warning.
- Replace travis with github actions

### Motivation and Context
To make testing easier.

fixes #780

Github actions sample run:
https://github.com/anajavi/react-datetime/runs/4204940938?check_suite_focus=true

### Checklist

```
[X] I have not included any built dist files (us maintainers do that prior to a new release)
[ ] I have added tests covering my changes
[X] All new and existing tests pass
[ ] My changes required the documentation to be updated
  [ ] I have updated the documentation accordingly
  [ ] I have updated the TypeScript 1.8 type definitions accordingly
  [ ] I have updated the TypeScript 2.0+ type definitions accordingly
```

### CODE REVIEW

**Comment by anajavi** [comment]
Dropped node 10 too as it is obsolete in one week.

**Comment by anajavi** [comment]
@arqex this fixes the CI, so that other PR's can be unblocked. Would you consider merging this?

**Comment by johnhunter** [comment]
Any news on this? The maintainers listed from `npm info react-datetime` are @arqex @simeg @layneanderson - anyone able to merge this? I also have a couple of suggestions for managing dependencies that might be worth considering https://github.com/arqex/react-datetime/issues/780

**Comment by johnhunter** [comment]
So this wasn't merged - what a shame 😞

**Pull request closed without merging**
