### PR TITLE
Fix error when new year's days are showing up (December -> January)

### PR DESCRIPTION
**Pull request by jugoncalves**
It fixes the bug when it's December and you click in (supposedly) January days and it goes to November.

### CODE REVIEW

**Comment by christopherscott** [comment]
:+1: to this

**Comment by BradHarris** [comment]
:+1: 

I opened an issue about this: https://github.com/arqex/react-datetime/issues/40

**Comment by Eruant** [comment]
Can we also get it published on npm?

Thanks

**Comment by sedenardi** [comment]
:+1:

**Comment by arqex** [comment]
Oh I forgot. Published. Did I say I am looking for a collaborator for this project?

**Comment by sedenardi** [comment]
@arqex Thanks dude.

I have a couple of enhancements I'd like to make to this eventually. Namely:
- Side-by-side date and time picker
- Position of popover element (right now it's just bottom, would like to specify [top, left, right, bottom])
- CSS tweaks (hover color for possible dates, cursor behavior, etc.)

I wouldn't mind taking on some (or all) of these enhancements myself. I was thinking of just submitting PRs as I go through them.

**Pull request merged**
