### PR TITLE
added css route for easier setup

### PR DESCRIPTION
**Pull request by orifmilod**
### Description
I have added the CSS line for importing styling in documentation

### Motivation and Context
I have added the CSS line for importing styling, which can be helpful with increasing the speed of setting up the package.

### Checklist
```
[X] All new and existing tests pass
[X] My changes required the documentation to be updated
[X] I have updated the documentation accordingly
```

### CODE REVIEW

**Comment by arqex** [comment]
Hey @orifmilod 

Thanks for the contribution, I think it's a great one.

The only think I don't feel it's needed is the extra indentation in the prop table. That table is going to change in the next version of the library and keep it indented is a bit annoying for me.

If you revert the indentation, I'll merge this PR straight away. Thanks.

**Comment by orifmilod** [comment]
> Hey @orifmilod
> 
> Thanks for the contribution, I think it's a great one.
> 
> The only think I don't feel it's needed is the extra indentation in the prop table. That table is going to change in the next version of the library and keep it indented is a bit annoying for me.
> 
> If you revert the indentation, I'll merge this PR straight away. Thanks.

**Comment by orifmilod** [comment]
@arqex I have accidentally closed the PR, by bad xd. but it's opened again, and the table indentation is reverted.

**Comment by orifmilod** [comment]
@arqex Any update in here?

**Comment by arqex** [comment]
Sorry for taking sooooo loooooong to accept the PR. And thank you very much for it.

**Pull request merged**
