### PR TITLE
Apply TimeConstraints after rerender component

### PR DESCRIPTION
**Pull request by Cript**
https://github.com/YouCanBookMe/react-datetime/issues/537

### CODE REVIEW

**Comment by spiroski** [comment]
Could we merge this, It is a nasty bug that prevents dynamic changes of time constraints.

**Comment by EmirGluhbegovic** [comment]
Please will this update be done.

**Comment by leonimurilo** [comment]
I really need this

**Comment by leonimurilo** [comment]
@arqex Could you check this please? It seems very simple and important.

**Comment by RobotnickIsrael** [comment]
I would like this fix merged as well please

**Comment by arqex** [comment]
Sorry for getting late into this PR but thanks!. Many changes happened since it was created and the issues are already fixed in the latest version. Closing it.

**Comment by entiendoNull** [comment]
Are you completely positive that this bug is fixed?
I am currently using `v.3.0.4` and I experience that new constraints, after re-rendering, are not taken into account.

I have checked so that my time constraint object updates correctly, but e.g. returning the following time constraint I can still e.g. toggle minutes to above 20.

```
{
    hours: {min: 0, max: 10, step: 1},
    minutes: {min: 0, max: 20, step: 1},
    seconds: {min: 0, max: 39, step: 1}
}
```

**Pull request closed without merging**
