### PR TITLE
Allow usage with react 18

### PR DESCRIPTION
**Pull request by alexander-schranz**
### Description

Allow usage with react 18.

### Motivation and Context

Avoid: "react-datetime@3.1.1 requires a peer of react@^16.5.0 || ^17.0.0 but none is installed"

### Checklist

```
[x] I have not included any built dist files (us maintainers do that prior to a new release)
[-] I have added tests covering my changes
[x] All new and existing tests pass
[-] My changes required the documentation to be updated
  [ ] I have updated the documentation accordingly
  [ ] I have updated the TypeScript 1.8 type definitions accordingly
  [ ] I have updated the TypeScript 2.0+ type definitions accordingly
```

### CODE REVIEW

**Review by bablukpik — APPROVED** [review]

**Comment by jedfong** [comment]
Any estimate on when this change will be merged/published?

**Comment by hasanbisha** [comment]
it any help needed with this pr? i can give a hand

**Comment by yadomi** [comment]
Hi @arqex, could this be merged ? Also, this one https://github.com/arqex/react-datetime/pull/789  should probably be closed in the mean time

**Comment by arqex** [comment]
Sorry for taking so long to merge 🙏  I've just published v3.2.0

**Comment by pladaria** [comment]
Ok, now the same for React19

**Comment by arqex** [comment]
I've just released a version 3.3.0 with react 19 as a peer dependency. I hope it works for you :)

**Comment by alexander-schranz** [comment]
That was fast @arqex thx.

**Pull request merged**
