### PR TITLE
Added `defaultTime` prop

### PR DESCRIPTION
**Pull request by shawninder**
### Description
The DateTime component now accepts an optional `defaultTime` prop which specifies which time to set when selecting a day.

### Motivation and Context
This is particularly useful if you're using two instances of the component to make a date-time **range** picker. In this case the *from* datetime picker can stay as-is, but the *to* datetime picker should default to the end of the day, not the beginning, so that you can just select a *from* day and a *to* day, and both will be included in the range.

### Checklist
I didn't finish this checklist, but I can finish it if there is any interest in merging this. Otherwise, this suits my needs so I would just leave it. If anyone else want to finish this checklist and send me a PR, that would be awesome.

[ ] I have added tests covering my changes
[ ] All new and existing tests pass
[x] My changes required the documentation to be updated
  [ ] I have updated the documentation accordingly
  [ ] I have updated the TypeScript 1.8 type definitions accordingly
  [ ] I have updated the TypeScript 2.0+ type definitions accordingly
```
### Additional notes
When cloning the original component (YouCanBookMe/react-datetime), a lot of tests didn't pass. I have not fixed them so they still fail here, but all the tests that passed before these changes still pass.

### CODE REVIEW

**Comment by shawninder** [comment]
This new feature was suggested here: https://github.com/YouCanBookMe/react-datetime/issues/401

**Comment by shawninder** [comment]
I am publishing this to a private npm repo, so don't forget to revert the name in the package before merging this PR

**Comment by simeg** [comment]
Hi @shawninder. Thanks for your contribution.

I think this would be a good feature to have. Although I don't want to merge this PR since it's really the first commit that is interesting, so I might just take your code and make my own PR. Hope that's ok with you. Thanks again for this nice feature. Keeping this PR open until someone fixes this.

**Comment by shawninder** [comment]
This has indeed become my own fork for my own uses, I apologize. If you make your own PR here with only that commit, please link to it here and I can deprecate/remove mine.

Another thing to consider is that this new feature has only been tested in the specific configuration in which I use react-datetime. Your mileage may vary.

Cheers!

**Comment by et304383** [comment]
Can we get some traction on this?  It's absurd that we cannot set this by now.

When a user picks a start and end date of the same date, it's assumed that it will filter based on a single day, but now with default behaviour it's a search of date between a start and end date that are identical, which means no results.  No one would ever want this as a desired behaviour.

**Comment by arqex** [comment]
Sorry for getting late into this PR but thanks!. Many changes happened since it was created and the issues are already fixed in the latest version. Closing it.

**Pull request closed without merging**
